# Generated by Django 3.1 on 2020-10-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=254)),
                ('level', models.IntegerField(choices=[(1, 'Level One'), (2, 'Level 2')], default=1)),
                ('required', models.BooleanField(default=True)),
            ],
        ),
    ]
