# Generated by Django 3.1 on 2020-10-04 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_auto_20201004_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitlist',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
