# Generated by Django 3.1 on 2020-10-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='hours_availble',
            new_name='hours_available',
        ),
    ]
