# Generated by Django 3.1 on 2020-10-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_auto_20201009_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteerhours',
            options={'verbose_name_plural': 'VolunteerHours'},
        ),
    ]
