# Generated by Django 3.1 on 2020-10-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Waitlist',
            new_name='Lecture',
        ),
    ]
